### PR TITLE
Add minutes for 12-06-2024 meeting

### PR DESCRIPTION
**Pull request by rpodcast**

### CODE REVIEW

**Comment by bms63** [comment]
Minutes look great - how do you view the site from netifly?  I was poking around logs but couldn't find a working url https://github.com/RConsortium/submissions-wg/actions/runs/12240585620/job/34143756390?pr=132

**Comment by bms63** [comment]
Should we starting looking into adding a spelling and link checker?

**Comment by rpodcast** [comment]
> Minutes look great - how do you view the site from netifly? I was poking around logs but couldn't find a working url https://github.com/RConsortium/submissions-wg/actions/runs/12240585620/job/34143756390?pr=132

I hope to make it more obvious but there is a button called View deployment in one of the PR comments above that should take you to the rendered Netlify site. I will work on a way to make it more obvious to the user.

image

**Comment by rpodcast** [comment]
> Should we starting looking into adding a spelling and link checker?

Absolutely! The same repo I drew upon for the Netflify deployment also has a template GH action for link checking. I'll add that later this month.

**Comment by bms63** [comment]
ah lol i see it now!!  but i get this :( 

image

**Comment by rpodcast** [comment]
> ah lol i see it now!! but i get this :(

That is very strange. I verified that I can view the preview deployment when logged in as a different GH account, as well as in a private browser window when not logged in to GitHub. I'd be glad to try and troubleshoot this with you on our Slack channel to see if we can diagnose the problem.

**Comment by vedhav** [comment]
I think Ben must have clicked the first deployment link which does not work. I get the broken page when I click the first link and it works when I click the latest one.
image

**Comment by bms63** [comment]
Thanks @vedhav!  I did not see that other button!!  it works for me

**Pull request merged**
